on: pull_request
name: Review
jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Changelog should be updated
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Git fetch
        run: git fetch

      - name: Check that changelog has been updated.
        run: git diff --exit-code origin/${{ github.base_ref }} -- CHANGELOG.md && exit 1 || exit 0

  # assets-coding-standards:
  #   name: Assets coding standards
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Coding standards
  #       run: |
  #         docker run --rm -v "$(pwd):/work" tmknom/prettier --check assets

  markdown-coding-standards:
    name: Markdown coding standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Coding standards
        run: |
          docker run --rm --volume $PWD:/md peterdavehello/markdownlint markdownlint --ignore vendor --ignore LICENSE.md '**/*.md'

  composer-normalize:
    name: composer-normalize
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - run: |
          docker run --user root --rm --volume ${PWD}:/app itkdev/php8.1-fpm:latest composer install
          docker run --user root --rm --volume ${PWD}:/app itkdev/php8.1-fpm:latest composer normalize

  coding-standards-php-cs-fixer:
    name: coding-standards-check/php-cs-fixer
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - run: |
          docker run --user root --rm --volume ${PWD}:/app itkdev/php8.1-fpm:latest composer install
          docker run --user root --rm --volume ${PWD}:/app itkdev/php8.1-fpm:latest composer coding-standards-check/php-cs-fixer

  coding-standards-twig-cs-fixer:
    name: coding-standards-check/twig-cs-fixer
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - run: |
          docker run --user root --rm --volume ${PWD}:/app itkdev/php8.1-fpm:latest composer install
          docker run --user root --rm --volume ${PWD}:/app itkdev/php8.1-fpm:latest composer coding-standards-check/twig-cs-fixer

  code-analysis-phpstan:
    name: code-analysis/phpstan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - run: |
          docker run --user root --rm --volume ${PWD}:/app itkdev/php8.1-fpm:latest composer install
          docker run --user root --rm --volume ${PWD}:/app itkdev/php8.1-fpm:latest composer code-analysis/phpstan
